---
- hosts: SW1
  gather_facts: false
  connection: network_cli

  tasks:
   - name: show command
     eos_command:
       commands: show run sec vrf HP
     register: OUTPUT

   - name: PRINT
     debug:
       var: OUTPUT

