---
- hosts: switch
  gather_facts: false
  connection: network_cli

  tasks:
   - name: enter into enable
     eos_command:
       commands: enable

   - name: create vlan
     eos_vlans:
       config:
         - vlan_id: 501
           name: CUST-501
           state: active

