---  
- hosts: SW1
  gather_facts: false
  connection: network_cli
  #ansible_become: yes
  #ansible_become_method: enable
  tasks:
   - name: 'enable'
     eos_command:
       commands: enable 
         
   - name: 'Create vlan'
     eos_vlan:
      vlan_id: 500
      name: vlan-500
      state: present
