---
- hosts: SW2
  gather_facts: false
  connection: network_cli

  #vars_files:
   #- "18v.yaml"

  tasks:
   - name: create vlan
     eos_vlans:
       config:
         - vlan_id: 501
           name: S-TEST
           state: active

