---
- hosts: "{{SW}}"
  gather_facts: false
  connection: network_cli

  vars_files:
   - ./DC_1_Underlay_Intent.json

  tasks:
    - name: Enable
      eos_command:
        commands: enable
        
#    - name:  ADC_Customer_Addition_Txt
#      template:
#        src:  ADC_Customer_Addition.j2
#        dest: ADC_Customer_Addition.txt
#      when: (Devices[SW]['device_role'] == 'leaf')
#      ignore_errors: yes

    - name:  ADC_Customer_Addition_Step1a.j2
      eos_config:
        src:  ADC_Customer_Addition_Step1a.j2
      when: (Devices[SW]['device_role'] == 'leaf')
      ignore_errors: yes

    - name:  ADC_Customer_Addition_Step1b.j2
      eos_config:
        src:  ADC_Customer_Addition_Step1b.j2
      when: (Devices[SW]['device_role'] == 'leaf')
      ignore_errors: yes

    - name:  ADC_Customer_Addition_Step1c.j2
      eos_config:
        src:  ADC_Customer_Addition_Step1c.j2
      when: (Devices[SW]['device_role'] == 'leaf')
      ignore_errors: yes

    - name:  ADC_Customer_Addition_Step1d.j2
      eos_config:
        src:  ADC_Customer_Addition_Step1d.j2
      when: (Devices[SW]['device_role'] == 'leaf')
      ignore_errors: yes







