---
- hosts: "{{SW}}"
  gather_facts: false
  connection: network_cli

  vars_files:
   - ./DC_1_Underlay_Intent.json

  tasks:
    - name: Enable
      eos_command:
        commands: enable

    - name:  ADC_Step_1_Underlay_P2P_Connections_Between_Spine_and_Leaf.j2
      eos_config:
        src:  ADC_Step_1_Underlay_P2P_Connections_Between_Spine_and_Leaf.j2
      when: (Devices[SW]['device_role'] == 'leaf' or 'spine')
      ignore_errors: yes      

    - name:  ADC_Step_2_Underlay_OSPF_Between_Spine_and_Leaf.j2
      eos_config:
        src:  ADC_Step_2_Underlay_OSPF_Between_Spine_and_Leaf.j2
      when: (Devices[SW]['device_role'] == 'leaf' or 'spine')
      ignore_errors: yes

    - name:  ADC_Step_3_Underlay_BGP_EVPN_Between_Spine_and_Leaf.j2
      eos_config:
        src:  ADC_Step_3_Underlay_BGP_EVPN_Between_Spine_and_Leaf.j2
      when: (Devices[SW]['device_role'] == 'leaf' or 'spine')
      ignore_errors: yes      

    - name:  ADC_Step_4_VXLAN_Config_in_Leaf.j2
      eos_config:
        src:  ADC_Step_4_VXLAN_Config_in_Leaf.j2
      when: (Devices[SW]['device_role'] == 'leaf')
      ignore_errors: yes

    - name:  ADC_Step_5a_Customer_Addition_Type5_Routes_VRF_Config_in_Leaf.j2
      eos_config:
        src:  ADC_Step_5a_Customer_Addition_Type5_Routes_VRF_Config_in_Leaf.j2
      when: (Devices[SW]['device_role'] == 'leaf')
      ignore_errors: yes
     
    - name:  ADC_Step_5b_Customer_Addition_Type5_Routes_BGP_in_Leaf.j2
      eos_config:
        src:  ADC_Step_5b_Customer_Addition_Type5_Routes_BGP_in_Leaf.j2
      when: (Devices[SW]['device_role'] == 'leaf')
      ignore_errors: yes

    - name:  ADC_Step_5c_Customer_Addition_Type2_Routes_VLAN_Config_in_Leaf.j2
      eos_config:
        src:  ADC_Step_5c_Customer_Addition_Type2_Routes_VLAN_Config_in_Leaf.j2
      when: (Devices[SW]['device_role'] == 'leaf')
      ignore_errors: yes

    - name:  ADC_Step_5d_Customer_Addition_Type2_Routes_BGP_Config_in_Leaf.j2
      eos_config:
        src:  ADC_Step_5d_Customer_Addition_Type2_Routes_BGP_Config_in_Leaf.j2
      when: (Devices[SW]['device_role'] == 'leaf')
      ignore_errors: yes









