---
- hosts: "{{SW}}"
  gather_facts: false
  connection: network_cli

  vars_files:
   - ./DC_1_Underlay_Intent.json

  tasks:
    - name: Enable
      eos_command:
        commands: enable
        
    - name:  ADC_Customer_Addition_Step1a_in_Leaf.j2
      eos_config:
        src:  ADC_Customer_Addition_Step1a_in_Leaf.j2
      when: (Devices[SW]['device_role'] == 'leaf')
      ignore_errors: yes

    - name:  ADC_Customer_Addition_Step1b_in_Leaf.j2
      eos_config:
        src:  ADC_Customer_Addition_Step1b_in_Leaf.j2
      when: (Devices[SW]['device_role'] == 'leaf')
      ignore_errors: yes

    - name:  ADC_Customer_Addition_Step1c_in_Leaf.j2
      eos_config:
        src:  ADC_Customer_Addition_Step1c_in_Leaf.j2
      when: (Devices[SW]['device_role'] == 'leaf')
      ignore_errors: yes

    - name:  ADC_Customer_Addition_Step1d_in_Leaf.j2
      eos_config:
        src:  ADC_Customer_Addition_Step1d_in_Leaf.j2
      when: (Devices[SW]['device_role'] == 'leaf')
      ignore_errors: yes

- hosts: "{{HOST}}"
  gather_facts: false
  connection: network_cli

  vars_files:
   - ./DC_1_Underlay_Intent.json

  tasks:
    - name: Enable
      eos_command:
        commands: enable
        
    - name:  ADC_Customer_Addition_Step2a_Type5_VLAN_in_Host.j2
      eos_config:
        src:  ADC_Customer_Addition_Step2a_Type5_VLAN_in_Host.j2
      when: (Devices[HOST]['device_role'] == 'host')
      ignore_errors: yes
      
    - name:  ADC_Customer_Addition_Step2b_Type2_VLAN_in_Host.j2
      eos_config:
        src:  ADC_Customer_Addition_Step2b_Type2_VLAN_in_Host.j2
      when: (Devices[HOST]['device_role'] == 'host')
      ignore_errors: yes
      
- hosts: "{{SL}}"
  gather_facts: false
  connection: network_cli

  vars_files:
   - ./DC_1_Underlay_Intent.json

  tasks:
    - name: Enable
      eos_command:
        commands: enable
        
    - name:  ADC_Customer_Addition_Step3a_SL_to_FW_in_Leaf.j2
      eos_config:
        src:  ADC_Customer_Addition_Step3a_SL_to_FW_in_Leaf.j2
      ignore_errors: yes
      

ADC_Customer_Addition_Step3b_FW_to_SL_in_FW.j2



- hosts: "{{FW}}"
  gather_facts: false
  connection: network_cli

  vars_files:
   - ./DC_1_Underlay_Intent.json

  tasks:
    - name: Enable
      eos_command:
        commands: enable
        
    - name:  ADC_Customer_Addition_Step3b_FW_to_SL_in_FW.j2
      eos_config:
        src:  ADC_Customer_Addition_Step3b_FW_to_SL_in_FW.j2
      ignore_errors: yes
      

