---
- hosts: "{{SW}}"
  gather_facts: false
  connection: network_cli

  vars_files:
   - ./DC_1_Underlay_Intent.yaml

  tasks:
    - name: Enable
      eos_command:
        commands: enable

#    - name: DC1_Underlay_Vxlan_CustomerAddition
#      eos_config:
#        src: DC1_Underlay_Vxlan_CustomerAddition.j2 
 
    - name: DC1_1_BGP
      eos_config:
        src: DC_1_BGP_Config.j2
        

    
    
    
