---
- hosts: SWITCH
  gather_facts: false
  connection: network_cli


  tasks:
    - name: Enable
      eos_command:
        commands: enable

    - name: Underlay
      eos_config:
        src: DC_Underlay.j2
