---
- hosts: SWITCH
  gather_facts: false
  connection: network_cli

  vars_files:
   - ./DC_1_Underlay_Intent.yaml

  tasks:
    - name: Enable
      eos_command:
        commands: enable

    - name: Underlay
      eos_config:
        src: DC_Underlay.j2
