---
- hosts: switch
  gather_facts: false
  connection: network_cli

  tasks:

   - name: to enable
     eos_command:
       commands: enable

   - name: VLAN CREATION
     eos_vlans:
       config:
         - vlan_id: "{{VLAN_ID}}"
           name: '{{C_NAME}}'
           state: active
