---
- hosts: switch
  gather_facts: false
  connection: network_cli

#  vars_files:
#   - ./dv.yaml

  tasks:
   - name: to enable
     eos_command:
       commands: enable

   - name: VRF DEFINITION
     eos_config:
       lines:
         - rd 1:{{C_ID}}
       parents:
         - vrf definition {{C_ID}}
     register: output

   - name: IP ROUTING ENABLEMENT
     eos_config:
       lines: ip routing vrf {{C_ID}}

   - name: BGP CONFIG
     eos_config:
       lines:
         - rd 1:{{C_ID}}
         - neighbor {{SW2_IP}} remote-as {{asn_num}}
         - neighbor {{SW2_IP}} update-source Vlan{{C_ID}}
         - neighbor {{SW2_IP}} ebgp-multihop
         - neighbor {{SW2_IP}} maximum-routes 12000
         - address-family ipv4
         - neighbor {{SW2_IP}} activate
       parents:
         - router bgp {{asn_num}}
         - vrf {{C_ID}}
     register: output

