---
- hosts: "{{LEAF_PAIR}}"
  gather_facts: false
  connection: network_cli

  tasks:
   - name: to enable
     eos_command:
       commands: enable

   - name: VLAN Configuration
     eos_config:
       lines:
         - vlan 4094
         - name MLGA-PEER
         - trunk group MLAG-PEER
       
   - name: VLAN INTERNFACE CONFIGURATION
     eos_config:
       lines:
         - int vlan 4094
         - des MLAG-PEER
         - mtu 9214
       parents:
         - interface vlan 4094

   - name: VLAN INTERNFACE CONFIGURATION LEAF1 IP
     eos_config:
       lines:
         - ip add 192.168.0.1/30
       parents:
         - interface vlan 4094
     when: ansible_leaf_type: 1

   - name: VLAN INTERNFACE CONFIGURATION LEAF2 IP
     eos_config:
       lines: 
         - ip add 192.168.0.2/30
       parents:
         - interface vlan 4094
     when: ansible_leaf_type: 2

   - name: PORT-CHANNEL INTERFACE CONFIGURATION
     eos_config:
       lines:
         - des Port-channel-between-Leafs
         - switchport mode trunk
         - switchport trunk group MLAG-PEER
       parents:
         - interface port-channel 1

