---
- hosts: "{{LEAF_PAIR}}"
  gather_facts: false
  connection: network_cli

  tasks:
   
   - name: to enable
     eos_command:
       commands: enable
         
   - name: EBGP CONFIG
     eos_config:
       lines:
         - neighbor BGP-EVPN peer group
         - neighbor BGP-EVPN remote-as 65000
         - neighbor BGP-EVPN update-source lo 0
         - neighbor BGP-EVPN ebgp-multihop 3
         - neighbor BGP-EVPN send-community extended

         - neighbor {{SPINE1_LOOP_0}} peer group BGP-EVPN
         - neighbor {{SPINE2_LOOP_0}} peer group BGP-EVPN

         - add evpn 
         - neighbor BGP-EVPN act
       parents:
         - router bgp {{ vars[LEAF_PAIR+'_ASN'] }}
  

- hosts: SPINE
  gather_facts: false
  connection: network_cli

  tasks:
   - name: to enable
     eos_command:
       commands: enable

   - name: BGP CONFIG
     eos_config:
       lines:
         - neighbor BGP-EVPN peer group
         - neighbor BGP-EVPN update-source lo 0
         - neighbor BGP-EVPN ebgp-multihop 3
         - neighbor BGP-EVPN send-community extended

         - neighbor {{ vars[LEAF_PAIR+'1_LOOP_0'] }} peer group BGP-EVPN
         - neighbor {{ vars[LEAF_PAIR+'1_LOOP_0'] }} remote-as {{ vars[LEAF_PAIR+'_ASN'] }}

         - neighbor {{ vars[LEAF_PAIR+'2_LOOP_0'] }} peer group BGP-EVPN
         - neighbor {{ vars[LEAF_PAIR+'2_LOOP_0'] }} remote-as {{ vars[LEAF_PAIR+'_ASN'] }}

         - add evpn 
         - neighbor BGP-EVPN act

       parents:
         - router bgp 65000
