---
- hosts: {{BL}}
  gather_facts: false
  connection: network_cli

  tasks:
 
   - name: to enable
     eos_command:
       commands: enable

   - name: VRF DEFINITION
     eos_config:
       lines:
         - rd {{RD}}:{{C_ID}}
       parents:
         - vrf definition C{{C_ID }}
                  
   #- name: VLAN CREATION
     #eos_vlans:
       #config:
         #- vlan_id: "{{VLAN_ID}}"
           #name: '{{C_NAME}}'
           #state: active
      
   - name: VLAN CREATION
     eos_config:
       lines:
         - vlan {{C_ID}}1, {{C_ID}}2  
         - description Yet to be updated
         
   - name: L3 VLAN INTERFACE 
     eos_config:
       lines:
         - vrf forwarding C{{C_ID}} 
         - ip address 101.10.11.11/24
       parents:
         - interface vlan {{C_ID}}1

   - name: VXLAN VTEP TUNNEL SETUP 
     eos_config:
       lines:
         - vxlan vrf C{{C_ID}} vni {{C_ID}}00 
       parents:
         - interface vxlan 1
         
   - name: BGP CONFIG
     eos_config:
       lines:
         - rd {{RD}}:{{C_ID}}
         - neighbor {{SW2_IP}} remote-as 65002
         - neighbor {{SW2_IP}} update-source Vlan{{VLAN_ID}}
         - neighbor {{SW2_IP}} ebgp-multihop
         - neighbor {{SW2_IP}} maximum-routes 12000
         - address-family ipv4
         - neighbor {{SW2_IP}} activate
       parents:
         - router bgp 65001
         - vrf {{C_NAME}}

