---
- hosts: SW1
  gather_facts: false
  connection: network_cli

  #vars:
     #"FS_PATH": ${} 
 
  tasks:
   - name: to enable
     eos_command:
       commands: enable
        
   - name: Vlan creation
     eos_vlans:
       config:
         - vlan_id: "{{VLAN_ID}}"
           name: "{{ C_NAME }}"
           state: active

