---
- hosts: SW1
  gather_facts: false
  connection: network_cli

  tasks:

   - name: to enable
     eos_command:
       commands: enable

   - name: VLAN CREATION
     eos_vlans:
       config:
         - vlan_id: "{{VLAN_ID}}"
           name: '{{C_NAME}}'
           state: active

   - name: VRF DEFINITION
     eos_config:
       lines:
         - rd 1:{{VLAN_ID}}
       parents:
         - vrf definition {{C_NAME}}
     register: output

   - name: IP ROUTING ENABLEMENT
     eos_config:
       lines: ip routing vrf {{C_NAME}}

   - name: INTERNFACE CONFIGURATION
     eos_config:
       lines:
         - vrf forwarding {{C_NAME}}
         - description {{C_NAME}}
         - ip address {{SW1_IP}}/24
       parents:
         - interface vlan{{VLAN_ID}}
     register: output

   - name: BGP CONFIG
     eos_config:
       lines:
         - rd 1:{{VLAN_ID}}
         - neighbor {{SW2_IP}} remote-as 65002
         - neighbor {{SW2_IP}} update-source Vlan{{VLAN_ID}}
         - neighbor {{SW2_IP}} ebgp-multihop
         - neighbor {{SW2_IP}} maximum-routes 12000
         - address-family ipv4
         - neighbor {{SW2_IP}} activate
       parents:
         - router bgp 65001
         - vrf forwarding {{C_NAME}}
     register: output

- hosts: SW2
  gather_facts: false
  connection: network_cli

  tasks:

   - name: to enable
     eos_command:
       commands: enable

   - name: VLAN CREATION
     eos_vlans:
       config:
         - vlan_id: "{{VLAN_ID}}"
           name: '{{C_NAME}}'
           state: active

   - name: VRF DEFINITION
     eos_config:
       lines:
         - rd 2:{{VLAN_ID}}
       parents:
         - vrf definition {{C_NAME}}
     register: output

   - name: IP ROUTING ENABLEMENT
     eos_config:
       lines: ip routing vrf {{C_NAME}}

   - name: INTERNFACE CONFIGURATION
     eos_config:
       lines:
         - vrf forwarding {{C_NAME}}
         - description {{C_NAME}}
         - ip address {{SW2_IP}}/24
       parents:
         - interface vlan{{VLAN_ID}}
     register: output

   - name: BGP CONFIG
     eos_config:
       lines:
         - rd 2:{{VLAN_ID}}
         - neighbor {{SW1_IP}} remote-as 65001
         - neighbor {{SW1_IP}} update-source Vlan{{VLAN_ID}}
         - neighbor {{SW1_IP}} ebgp-multihop
         - neighbor {{SW1_IP}} maximum-routes 12000
         - address-family ipv4
         - neighbor {{SW1_IP}} activate
       parents:
         - router bgp 65002
         - vrf forwarding {{C_NAME}}
     register: output
